[workspace]
resolver = "2"
members = [
    "core",
    "cpu-z80",
    "cpu-6502",
    "machine-spectrum",
    "machine-c64",
    "machine-c128",
    "machine-nes",
    "runner-lib",
    "spectrum-runner",
    "c64-runner",
]
