[package]
name = "runner-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
emu-core = { path = "../core" }
winit = "0.30"
pixels = "0.15"
bytemuck = { version = "1.14", features = ["derive"] }
cpal = "0.15"
ringbuf = "0.4"
gilrs = "0.11"
