[package]
name = "machine-amiga"
version = "0.1.0"
edition = "2024"

[dependencies]
emu-core = { path = "../emu-core" }
motorola-68000 = { path = "../motorola-68000" }
mos-cia-8520 = { path = "../mos-cia-8520" }
commodore-paula-8364 = { path = "../commodore-paula-8364" }
commodore-agnus-ocs = { path = "../commodore-agnus-ocs" }
commodore-denise-ocs = { path = "../commodore-denise-ocs" }
commodore-agnus-ecs = { path = "../commodore-agnus-ecs" }
commodore-denise-ecs = { path = "../commodore-denise-ecs" }
format-adf = { path = "../format-adf" }
drive-amiga-floppy = { path = "../drive-amiga-floppy" }
peripheral-amiga-keyboard = { path = "../peripheral-amiga-keyboard" }

[dev-dependencies]
png = "0.17"

[lib]
name = "machine_amiga"
path = "src/lib.rs"
