[package]
name = "emu-amiga-rock"
version = "0.1.0"
edition = "2021"

[dependencies]
emu-core = { path = "../emu-core" }
motorola-68000 = { path = "../motorola-68000" }

[dev-dependencies]
png = "0.17"

[lib]
name = "emu_amiga_rock"
path = "src/lib.rs"
