[package]
name = "motorola-68000"
description = "Cycle-accurate Motorola 68000 CPU emulator"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
emu-core = { path = "../emu-core" }

[lib]
name = "motorola_68000"
path = "src/lib.rs"
