[package]
name = "runner"
version = "0.1.0"
edition = "2024"

[dependencies]
machine-spectrum = { path = "../machine-spectrum" }
winit = "0.30"
pixels = "0.15"
bytemuck = { version = "1.14", features = ["derive"] }
cpal = "0.15"
ringbuf = "0.4"
gilrs = "0.11"
